TYPE_STRING = "STRING",
TYPE_NUMERIC = "NUMERIC"
TYPE_BOOLEAN = "BOOLEAN"
TYPE_LIST = "LIST"
TYPE_BLOCK = "BLOCK"
TYPE_EXPRESSION = "EXPRESSION"

TYPES = [TYPE_STRING, TYPE_NUMERIC, TYPE_BOOLEAN, TYPE_LIST]